[parity]
chain = "genesis.json"

[rpc]
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[mining]
reseal_on_txs = "none"
reseal_max_period = 60000

[misc]
log_file = "parity.log"

[network]
reserved_peers = "nodes.txt"