[parity]
chain = "genesis.json"
identity = "bitsign-node"

[network]
discovery = true
reserved_peers = "nodes.txt"

[rpc]
interface = "all"
cors = ["all"]
hosts = ["all"]
apis = ["safe"]

[websockets]
interface = "all"

[misc]
logging = "own_tx=trace"
log_file = "parity.log"
color = true