[parity]
chain = "genesis.json"
identity = "bitsign-node"

[account]
unlock = ["ETH_MINER_ACCOUNT"]
password = ["password.txt"]

[ui]
disable = true

[mining]
author = "ETH_MINER_ACCOUNT"
engine_signer = "ETH_MINER_ACCOUNT"
reseal_max_period = 30000

[footprint]
tracing = "on"
fat_db = "on"
pruning = "archive"

[network]
reserved_peers = "nodes.txt"
discovery = true

[misc]
logging = "own_tx=trace"
log_file = "parity.log"
color = true
