version: '3'
services:
  bitsign-node:
    build: .
    restart: unless-stopped
    environment:
      - NODE_NAME=${NODE_NAME}
      - NODE_TYPE=${NODE_TYPE}
    volumes:
      - bitsign-federation-data:/data
volumes:
    bitsign-federation-data: