version: '3'
services:
    bitsign-node:
        image: cryptologic/bitsign-node:${TAG}
        restart: unless-stopped
        environment:
            - NODE_NAME=${NODE_NAME}
        volumes:
            - bitsign-federation-data:/data

volumes:
    bitsign-federation-data:
